Repository 1crowie1/SIS-realestate, pull requests merged in 2022-10, with the labels that each got.

#59 Harrison ml
  .gitignore
  Recommendation/cluster.py
  Recommendation/main.py
  Recommendation/model.py
  algorithm/cluster.py
  algorithm/main.py
Labels: feature, Backend, High Priority

#62 Working Machine Learning Clusters - Centroids Visualised
  Recommendation/cluster.py
Labels: feature, Backend, Medium Priority

#63 Initial Cluster Updation Framework
  Recommendation/cluster.py
Labels: feature, Backend, Medium Priority

#66 Final Machine Learning
  Recommendation/cluster.py
Labels: feature, Backend, High Priority

#71 Preferences API Endpoints
  backend/app.js
  backend/package-lock.json
  backend/routes/recommendation.js
Labels: feature, devOps, Frontend, Backend, High Priority

#72 Frontend dev
  front-end/src/components/recommendations/recommendations.js
  front-end/src/util/RealestateUtil.js
Labels: Frontend, High Priority

#76 Frontend dev
  front-end/src/components/heatmap/heatmap.css
  front-end/src/components/heatmap/heatmap.jsx
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/listingCard.js
  front-end/src/components/results/priceBreakdown.js
  front-end/src/components/results/results.js
  front-end/src/components/results/suburbBreakdown.js
  front-end/src/util/RealestateUtil.js
Labels: feature, Frontend

#78 On Click Results Event
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/results.js
  front-end/src/util/RealestateUtil.js
Labels: Frontend, High Priority

#79 Frontend dev
  front-end/package.json
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/listingCard.js
  front-end/src/components/results/results.js
  front-end/src/util/RealestateUtil.js
Labels: Frontend, High Priority

#81 Fix Results to Only Display Once Button is Clicked
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/results.js
Labels: feature, Frontend, High Priority

#86 Frontend dev
  backend/app.js
  backend/routes/recommendation.js
  backend/routes/suburbsWithAverages.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/components/footer.js
  front-end/src/components/header.js
  front-end/src/components/heatmap/example-heatmap.js
  front-end/src/components/heatmap/heatmap.js
  front-end/src/components/heatmap/heatmap.jsx
  front-end/src/components/heatmap/legend.js
  front-end/src/components/heatmap/results-heatmap.js
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/priceBreakdown.js
  front-end/src/components/results/results.css
  front-end/src/components/results/results.js
  front-end/src/components/results/suburbBreakdown.js
  front-end/src/images/home_finder_4.svg
  front-end/src/util/RealestateUtil.js
Labels: bug, help wanted, feature, devOps, Frontend, Backend, High Priority

#87 Frontend dev
  backend/package-lock.json
  backend/package.json
  backend/routes/heatmap.js
  backend/routes/recommendation.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/heatmap/results-heatmap.js
  front-end/src/components/recommendations/recommendations.css
  front-end/src/components/recommendations/recommendations.js
  front-end/src/components/results/listingCard.js
  front-end/src/components/results/priceBreakdown.js
  front-end/src/components/results/results.js
  front-end/src/components/results/suburbBreakdown.js
  front-end/src/util/RealestateUtil.js
Labels: bug, documentation, feature, Frontend, Backend, High Priority
