Repository 1crowie1/SIS-realestate, pull requests merged in 2022-09, with the labels that each got.

#42 Create Results Page Wireframe.pdf
  Documentation/Design/Wireframe Prototypes/Results Page Wireframe with slidebar and colour.pdf
  Documentation/Design/Wireframe Prototypes/Results Page Wireframe with slidebar.pdf
  Documentation/Design/Wireframe Prototypes/Results Page Wireframe.pdf
Labels: Frontend

#47 Initialise frontend
  front-end/images/1.png
  front-end/images/2.png
  front-end/images/3.png
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/homefinder1.png
Labels: Frontend

#51 Meeting minutes for Sprint 2
  Documentation/Meeting Minutes/20220817 - Stand-up Meeting Note.docx
  Documentation/Meeting Minutes/20220819 - Stand-up Meeting Note.docx
  Documentation/Meeting Minutes/20220821 - Stand-up Meeting Note.docx
  Documentation/Meeting Minutes/20220824 - Stand-up Meeting Note.docx
Labels: Frontend

#53 Initialise frontend
  front-end/src/App.css
  front-end/src/App.js
Labels: Frontend, Medium Priority

#48 In-depth algorithm design documentation
  Documentation/Design/algorithm_design_plan.docx
Labels: documentation, Backend, Medium Priority, Low Priority
